jobs/urls.py
from django.urls import path
from . import views
from .views import JobListView, JobDetailView, JobApplyView

app_name = "services"

urlpatterns = [
    # TODO: services, news, career will be moved to a django app.
    # path('home/', views.home, name='home'), # TODO: remove this path when production
    # level 1 pages
    # path('', views.index, name='index'),
    # path('', views.services, name='index'),
    # path('case-studies/', views.case_studies, name='case_studies'),
    # path('news-and-events/', views.news_and_events, name='news_and_events'),
    # path('', views.career, name='career'), # path('career/', views.career, name='career'), # Replaced by CBV.
    path('', JobListView.as_view(), name='career'),
    # path('about/', views.about, name='about'),
    # path('contact/', views.contact, name='contact'),
    # path('privacy/', views.privacy, name='privacy'),
    # path('terms-and-conditions/', views.terms_and_conditions, name='terms_and_conditions'),
    
    # level 2 pages
    path('job/<int:pk>/', JobDetailView.as_view(), name='job_detail'),
    path('job/<int:pk>/apply/', JobApplyView.as_view(), name='job_apply'), # path('career/apply-now/', views.apply_now, name='apply_now'),
    # path('about/company-profile/', views.company_profile, name='company_profile'),
    # path('about/management-team/', views.management_team, name='management_team'),
    # path('about/investor-relations/', views.investor_relations, name='investor_relations'),
    # path('about/corprate-social-responsibility/', views.corprate_social_responsibility, name='corprate_social_responsibility'),
]
"""
URLs:
@see mysite:urls
"""

revenue_engine/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mysite.urls', namespace='mysite')), # General site
    path('services/', include('services.urls', namespace='services')), # Services pages
    path('news/', include('news.urls', namespace='news')), # News pages
    path('career/', include('jobs.urls', namespace='jobs')), # News pages
]

jobs/models.py
from django.db import models
from django.conf import settings # https://docs.djangoproject.com/en/2.2/topics/settings/
from django.urls import reverse

from mysite.models import Location, Status

User = settings.AUTH_USER_MODEL
# Create your models here.
# class Question(models.Model):
#     question_text   = models.CharField(max_length=200)
#     pub_date        = models.DateTimeField('date published')


# class Choice(models.Model):
#     question        = models.ForeignKey(Question, on_delete=models.CASCADE)
#     choice_text     = models.CharField(max_length=200)
#     votes           = models.IntegerField(default=0)

# ----
class JobType(models.Model):
    job_type        = models.CharField(max_length=200)
    created_at      = models.DateTimeField(auto_now_add=True)
    # created_by      = models.ForeignKey(User, on_delete=models.SET_DEFAULT, default=1, related_name='users')
    created_by      = models.ForeignKey(User, on_delete=models.SET_DEFAULT, default=1)
    status          = models.ForeignKey(Status, on_delete=models.SET_DEFAULT, default=2)

    def __str__(self):
        return self.job_type

class Category(models.Model):
    job_category    = models.CharField(max_length=200)
    created_at      = models.DateTimeField(auto_now_add=True)
    created_by      = models.ForeignKey(User, on_delete=models.SET_DEFAULT, default=1)
    status          = models.ForeignKey(Status, on_delete=models.SET_DEFAULT, default=2)

    def __str__(self):
        return self.job_category
    
class Post(models.Model):
    job_id          = models.CharField(max_length=200)
    created_by      = models.ForeignKey(User, on_delete=models.SET_DEFAULT, default=1)
    created_at      = models.DateTimeField(auto_now_add=True)
    # update_at  =
    # update_by  =
    location        = models.ForeignKey(Location, on_delete=models.SET_DEFAULT, default=1)
    job_type        = models.ForeignKey(JobType, on_delete=models.CASCADE)
    category        = models.ForeignKey(Category, on_delete=models.CASCADE)
    title           = models.CharField(max_length=200)
    description     = models.TextField(max_length=1000)
    job_id          = models.CharField(max_length=200)
    # responsibilities =    # TODO: unknown relationship since no model Services
    # equirements =         # TODO: relationship since no model Services
    # featured_job    = models.CharField(max_length=200)
    is_featured_job    = models.BooleanField(default=False)
    status          = models.ForeignKey(Status, on_delete=models.SET_DEFAULT, default=2)

    def __str__(self):
        return self.title
    
class ApplicationSource(models.Model):
    source          = models.CharField(max_length=255)
    created_at      = models.DateTimeField(auto_now_add=True)
    created_by      = models.ForeignKey(User, on_delete=models.SET_DEFAULT, default=1)
    status          = models.ForeignKey(Status, on_delete=models.SET_DEFAULT, default=2)

    def __str__(self):
        return self.source
    
class Application(models.Model):
    LOCATION_CHOICES = [ # This location is not the location defined in mysite.Location
        ('HK', 'Hong Kong'),
        ('SG', 'Singapore'),
        ('JP', 'Japan'),
        ('AU', 'Australia'),
        ('IN', 'India'),
        ('CN', 'China'),
        ('OT', 'Others'),
    ]
    
    AVAILABILITY_CHOICES = [
        ('IM', 'Immediately'),
        ('2W', '2 Weeks'),
        ('1M', '1 Month'),
        ('2M', '2 Months'),
    ]
    source          = models.ForeignKey(ApplicationSource, on_delete=models.SET_DEFAULT, default=1)
    # location        = models.ForeignKey(Location, on_delete=models.SET_DEFAULT, default=1)
    location        = models.CharField(max_length=2, choices=LOCATION_CHOICES, default='HK') # This 'location' is not the location defined in mysite.Location.
    created_at      = models.DateTimeField(auto_now_add=True)
    job_id          = models.CharField(max_length=200)
    first_name      = models.CharField(max_length=200)
    last_name       = models.CharField(max_length=200)
    email           = models.EmailField(max_length=254)
    telephone       = models.CharField(max_length=30)
    availability    = models.CharField(max_length=2, choices=AVAILABILITY_CHOICES, default='IM')

    def __str__(self):
        return self.id
    
    def get_absolute_url(self): # Google:django CreateView example -> https://www.agiliq.com/blog/2019/01/django-createview/
        # return reverse('jobs:job_detail', args=[str(self.job_id)])
        return reverse('jobs:career')

jobs/views.py
from django.shortcuts import render
from django.views import View
from django.views.generic import TemplateView, ListView, DetailView, UpdateView
from django.views.generic.edit import CreateView

from .models import Post, Application
# Create your views here.
# def career(request):
#     """The Career home page."""
#     return render(request, 'jobs/career.html')
#
# def apply_now(request):
#     """The apply_now page."""
#     return render(request, 'jobs/apply_now.html')

## CBV
class JobListView(ListView):
    """Show a list of jobs.
    
    The Career home page.
    """
    model = Post
    template_name = "jobs/career_.html"
    context_object_name = 'posts'

# level 2 pages
class JobDetailView(DetailView):
    """A job with its detail. Take an id and give a job."""
    model = Post
    template_name = "jobs/jobs_details_.html"
    context_object_name = 'post'

class JobApplyView(CreateView):
    """Submit to apply for a job."""
    model = Application
    template_name = "jobs/apply_.html"
    fields = ["first_name", "last_name", "email", "telephone", "location", "availability"]

jobs/templates/jobs/apply.html
{% extends "mysite/base_mysite.html" %}
{% load static %}

{% block title %}Welcome To ITCS Group - Apply for a job{% endblock title %}

{% block content %}
  <!-- ======== Content ======== -->
  <div id="content">
    <div class="container">
      <!-- Sign Up form -->
      <form class="form-login form-wrapper form-large" role="form">
        <h3 class="title-divider">
          <h5 class="my-0 text-primary" align="center">
              <i class="fas fa-map-pin"></i> Hong Kong &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
              <i class="fas fa-suitcase"></i> Software Development &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
              <i class="fas fa-list-alt"></i> Contract &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
          </h5>
          <hr class="hr-teal op-4 hr-lg w-100 mx-auto my-4" />
          <small class="mt-4">You are sending your application for this role. Please fill out your application below and attach your CV.</small><br><br>
        </h3>
        <h5>
        Applicant Information
        </h5>
        <div class="form-group">
          <label class="sr-only" for="signup-first-name-page">First Name</label>
          <input type="text" class="form-control" id="signup-first-name-page" placeholder="First name">
        </div>
        <div class="form-group">
          <label class="sr-only" for="signup-last-name-page">Last Name</label>
          <input type="text" class="form-control" id="signup-last-name-page" placeholder="Last name">
        </div>
        <div class="form-group">
          <label class="sr-only" for="signup-email-page">Email address</label>
          <input type="email" class="form-control" id="signup-email-page" placeholder="Email address">
        </div>
        <div class="form-group">
          <label class="sr-only" for="signup-email-page">Phone</label>
          <input type="phone" class="form-control" id="signup-phone-page" placeholder="Phone">
        </div>
        <div class="form-group">
          <label class="sr-only" for="signup-availability-page">Availability</label>
          <select class="form-control mb-3 mr-sm-2 mb-sm-0" id="signup-availability-page" placeholder="Availability">
            <option value="0" selected disabled>Availability</option>
            <option value="1">Immediately</option>
            <option value="2">2 weeks</option>
            <option value="3">1 month</option>
            <option value="4">2 months</option>
          </select>
        </div>
        <div class="form-group">
          <label class="sr-only" for="signup-location-page">Current location</label>
          <select class="form-control mb-3 mr-sm-2 mb-sm-0" id="signup-location-page" placeholder="Location">
            <option value="0" selected disabled>Current location</option>
            <option value="1">Hong Kong</option>
            <option value="2">Singapore</option>
            <option value="3">Japan</option>
            <option value="2">Australia</option>
            <option value="3">India</option>
            <option value="2">China</option>
            <option value="3">Others</option>
          </select>
        </div>
        <h5>
        Attach your CV
        </h5>
        <div class="form-group">
          <input type="file" class="form-control-file" id="exampleInputFile" aria-describedby="fileHelp">
          <small id="fileHelp" class="form-text text-muted">Please attach your CV in PDF, DOC, or DOCX.</small>
        </div>
        <hr />
        <div class="form-check">
          <label class="form-check-label">
              <input type="checkbox" value="term" class="form-check-input">
              I state that all the information and data above is accurate and truthful.
          </label> <br>
          <label class="form-check-label">
              <input type="checkbox" value="term" class="form-check-input">
              I authorize ITCS group to contact me for further opportunities.
          </label> <br>
          <label class="form-check-label">
              <input type="checkbox" value="term" class="form-check-input">
              I agree with the <a href="termsandconditions.html" target="_blank">Terms of Use</a> and <a href="privacypolicy.html" target="_blank">Privacy Policy</a>. 
          </label>
        </div>
        <hr />
        <center> <button class="btn btn-primary" type="submit">Send</button> </center>
      </form>
    </div>
  </div>
  <!-- ======== End Content ======== -->

    <!-- Project Calculation - this appears the the bottom of the page once you scroll down -->
    <div class="w-100 py-3 pos-fixed pos-zindex-20 pos-b scroll-state-hidden bg-white bg-shadow" data-scroll="scroll-state" data-scroll-amount="120" data-scroll-setting='{"effectIn":"slideInUp", "effectOut":"slideOutDown", "effectDuration":"0.3", "breakpoint":"992"}'>
      <div class="container d-flex flex-column flex-lg-row text-center justify-content-center align-items-center">
        <p class="d-lg-inline-block mr-lg-3 text-dark my-0">Apply for a <strong>different job?</strong></p>
        <p class="d-lg-inline-block text-sm text-dark op-8 my-0"><a href="career.html" class="mt-2 mt-lg-0 btn btn-primary border-w-2 btn-rounded px-4 py-2 font-weight-bold text-uppercase">Job list</a></p>
      </div>
      <a href="#top" class="btn btn-icon btn-dark pos-fixed pos-b pos-r mr-3 mb-3 scroll-state-hidden" title="Back to top" data-scroll="scroll-state"><i class="fa fa-chevron-up"></i></a>
    </div>
  <!-- #Content -->
{% endblock content %}

jobs/templates/jobs/apply_.html
{% extends "mysite/base_mysite.html" %}
{% load static %}

{% block title %}Welcome To ITCS Group - Apply for a job{% endblock title %}

{% block content %}
  <!-- ======== Content ======== -->
<!-- templates/post_new.html -->
    <h1>Apply Job</h1>
    <form action="" method="post">{% csrf_token %}
      {{ form.as_p }}
      <input type="submit" value="Apply Job!" />
    </form>
  <!-- #Content -->
{% endblock content %}

jobs/templates/jobs/apply_now.html
{% extends "mysite/base_mysite.html" %}
{% load static %}

{% block title %}Welcome To ITCS Group - Apply for a job{% endblock title %}

{% block content %}
  <!-- ======== Content ======== -->
  <div id="content">
    <div class="container">
      <!-- Sign Up form -->
      <form class="form-login form-wrapper form-large" role="form">
        <h3 class="title-divider">
          <h5 class="my-0 text-primary" align="center">
              <i class="fas fa-map-pin"></i> Hong Kong &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
              <i class="fas fa-suitcase"></i> Software Development &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
              <i class="fas fa-list-alt"></i> Contract &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
          </h5>
          <hr class="hr-teal op-4 hr-lg w-100 mx-auto my-4" />
          <small class="mt-4">You are sending your application for this role. Please fill out your application below and attach your CV.</small><br><br>
        </h3>
        <h5>
        Applicant Information
        </h5>
        <div class="form-group">
          <label class="sr-only" for="signup-first-name-page">First Name</label>
          <input type="text" class="form-control" id="signup-first-name-page" placeholder="First name">
        </div>
        <div class="form-group">
          <label class="sr-only" for="signup-last-name-page">Last Name</label>
          <input type="text" class="form-control" id="signup-last-name-page" placeholder="Last name">
        </div>
        <div class="form-group">
          <label class="sr-only" for="signup-email-page">Email address</label>
          <input type="email" class="form-control" id="signup-email-page" placeholder="Email address">
        </div>
        <div class="form-group">
          <label class="sr-only" for="signup-email-page">Phone</label>
          <input type="phone" class="form-control" id="signup-phone-page" placeholder="Phone">
        </div>
        <div class="form-group">
          <label class="sr-only" for="signup-availability-page">Availability</label>
          <select class="form-control mb-3 mr-sm-2 mb-sm-0" id="signup-availability-page" placeholder="Availability">
            <option value="0" selected disabled>Availability</option>
            <option value="1">Immediately</option>
            <option value="2">2 weeks</option>
            <option value="3">1 month</option>
            <option value="4">2 months</option>
          </select>
        </div>
        <div class="form-group">
          <label class="sr-only" for="signup-location-page">Current location</label>
          <select class="form-control mb-3 mr-sm-2 mb-sm-0" id="signup-location-page" placeholder="Location">
            <option value="0" selected disabled>Current location</option>
            <option value="1">Hong Kong</option>
            <option value="2">Singapore</option>
            <option value="3">Japan</option>
            <option value="2">Australia</option>
            <option value="3">India</option>
            <option value="2">China</option>
            <option value="3">Others</option>
          </select>
        </div>
        <h5>
        Attach your CV
        </h5>
        <div class="form-group">
          <input type="file" class="form-control-file" id="exampleInputFile" aria-describedby="fileHelp">
          <small id="fileHelp" class="form-text text-muted">Please attach your CV in PDF, DOC, or DOCX.</small>
        </div>
        <hr />
        <div class="form-check">
          <label class="form-check-label">
              <input type="checkbox" value="term" class="form-check-input">
              I state that all the information and data above is accurate and truthful.
          </label> <br>
          <label class="form-check-label">
              <input type="checkbox" value="term" class="form-check-input">
              I authorize ITCS group to contact me for further opportunities.
          </label> <br>
          <label class="form-check-label">
              <input type="checkbox" value="term" class="form-check-input">
              I agree with the <a href="termsandconditions.html" target="_blank">Terms of Use</a> and <a href="privacypolicy.html" target="_blank">Privacy Policy</a>. 
          </label>
        </div>
        <hr />
        <center> <button class="btn btn-primary" type="submit">Send</button> </center>
      </form>
    </div>
  </div>
  <!-- ======== End Content ======== -->

    <!-- Project Calculation - this appears the the bottom of the page once you scroll down -->
    <div class="w-100 py-3 pos-fixed pos-zindex-20 pos-b scroll-state-hidden bg-white bg-shadow" data-scroll="scroll-state" data-scroll-amount="120" data-scroll-setting='{"effectIn":"slideInUp", "effectOut":"slideOutDown", "effectDuration":"0.3", "breakpoint":"992"}'>
      <div class="container d-flex flex-column flex-lg-row text-center justify-content-center align-items-center">
        <p class="d-lg-inline-block mr-lg-3 text-dark my-0">Apply for a <strong>different job?</strong></p>
        <p class="d-lg-inline-block text-sm text-dark op-8 my-0"><a href="career.html" class="mt-2 mt-lg-0 btn btn-primary border-w-2 btn-rounded px-4 py-2 font-weight-bold text-uppercase">Job list</a></p>
      </div>
      <a href="#top" class="btn btn-icon btn-dark pos-fixed pos-b pos-r mr-3 mb-3 scroll-state-hidden" title="Back to top" data-scroll="scroll-state"><i class="fa fa-chevron-up"></i></a>
    </div>
  <!-- #Content -->
{% endblock content %}

jobs/templates/jobs/career_.html
{% extends "mysite/base_mysite.html" %}
{% load static %}

{% block title %}Welcome To ITCS Group - Career{% endblock title %}

{% block content %}

  <!-- ======== @Region: #content ======== -->
<p>{{ posts }}</p>
{% comment %} 1. Showing all jobs.{% endcomment %}
<p>All jobs</p>
<ul>
{% for post in posts %}
  <li>
  {{ post.title }}
  {{ post.is_featured_job }}
  </li>
{% endfor %}
</ul>

{% comment %} 2. Filter jobs. {% endcomment %}
<p>All jobs - with filter "is_featured_job"</p>
<ul>
{% for post in posts %}
  {% if post %}
    <li>{{ post.title }} - **Featured job** </li>
  {% else %}
    <li>{{ post.title }} - Not a featured job</li>
  {% endif %}
{% endfor %}
</ul>


{% comment %} 3. Filter jobs with links to job detail. {% endcomment %}
<p>All jobs - with filter "is_featured_job"</p>
<ul>
{% for post in posts %}
  {% if post %}
    <li><a href="{% url 'jobs:job_detail' post.pk %}">{{ post.title }}</a> - **Featured job** </li>
  {% else %}
    <li><a href="{% url 'jobs:job_detail' post.pk %}">{{ post.title }}</a> - Not a featured job</li>
  {% endif %}
{% endfor %}
</ul>
  <!-- #Content -->
{% endblock content %}

jobs/templates/jobs/jobs_details_.html
{% extends "mysite/base_mysite.html" %}
{% load static %}

{% block title %}Welcome To ITCS Group - Career{% endblock title %}

{% block content %}
  <!-- ======== @Region: #content ======== -->
  <div class="post-entry">
    <h2>ID_{{post.id}}: {{ post.title }}</h2>
    <p>{{ post.location }}</p>
    <p>{{ post.job_type }}</p>
    <p>{{ post.job_id }}</p>
    <p>{{ post.status }}</p>
  </div>

  <div class="nav-right">
    <a href="{% url 'jobs:job_apply' post.pk %}">+ Apply Job +</a>
  </div>
  <!-- #Content -->
{% endblock content %}